name: Build Packages

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            os: "x86_64-linux"
            package: "go"
          - runner: macos-latest
            os: "aarch64-darwin"
            package: "go"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v15
        with:
          nix_config: |
            experimental-features = nix-command flakes

      - name: Show available packages
        run: |
          nix flake show

      - name: Build package
        run: |
          nix build .#packages.${{ matrix.os }}.${{ matrix.package }}
