name: Build Packages

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        os:
          - { runner: ubuntu-latest, os: "x86_64-linux" }
          - { runner: macos-latest, os: "x86_64-darwin" }
          - { runner: macos-latest, os: "aarch64-darwin" }
        package: ["go"]  # List of packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v15
        with:
          nix_config: |
            experimental-features = nix-command flakes

      - name: Show available packages
        run: |
          nix flake show

      - name: Build package
        run: |
          nix build .#packages.${{ matrix.os.os }}.${{ matrix.package }}
